name: 自动调整 PR 目标分支

on:
  pull_request_target:
    types: [opened, edited]

jobs:
  check-branch:
    name: 检查 PR 目标分支
    # PR 新建或编辑目标分支时，将官方仓库中的 PR 自动指向 dev 分支。
    if: ${{ github.repository_owner == 'siyuan-note' && (github.event.action == 'opened' || github.event.changes.base) }}
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: 调整目标分支
        uses: Vankka/pr-target-branch-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          target: master
          exclude: dev
          change-to: dev
          comment: |
              The base branch of this PR has been automatically changed to `dev`, please check that there are no merge conflicts.
              此 PR 的基础分支已自动更改为 `dev`，请检查是否存在合并冲突。